<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPpeFyN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPpeFyN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPpeFyN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPpeFyN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKPpeFyN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KPpeFyN',
    'container.build_id' => 'cda10bfd',
    'container.build_time' => 1649737290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPpeFyN');
