<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0mPOgaF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0mPOgaF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0mPOgaF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0mPOgaF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0mPOgaF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0mPOgaF',
    'container.build_id' => '5a8d2be8',
    'container.build_time' => 1650764155,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0mPOgaF');
