<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9si391i\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9si391i/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9si391i.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9si391i\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9si391i\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9si391i',
    'container.build_id' => 'b313f1df',
    'container.build_time' => 1650340335,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9si391i');
